[build]
  command = "npm run build"
  publish = ".next"
  edge_handlers = "src/edge-handlers"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_handlers]]
  path = "/*"
  handler = "deny-secret"