backend:
  name: git-gateway
  branch: main
collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Products" # Used in the UI
    folder: "products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}